# Generated by Django 5.2.4 on 2025-07-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microcontroller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(max_length=50, verbose_name='ID на экране')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP адрес')),
                ('min_pressure', models.FloatField(verbose_name='Минимальное давление')),
                ('max_pressure', models.FloatField(verbose_name='Максимальное давление')),
                ('min_temperature', models.FloatField(verbose_name='Минимальная температура')),
                ('max_temperature', models.FloatField(verbose_name='Максимальная температура')),
            ],
        ),
    ]
