# Generated by Django 5.2.4 on 2025-07-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microcontroller',
            name='display_id',
        ),
        migrations.RemoveField(
            model_name='microcontroller',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='microcontroller',
            name='max_temperature',
        ),
        migrations.RemoveField(
            model_name='microcontroller',
            name='min_temperature',
        ),
        migrations.AddField(
            model_name='microcontroller',
            name='ip',
            field=models.GenericIPAddressField(default=0, protocol='IPv4', verbose_name='IP-адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microcontroller',
            name='max_temp',
            field=models.FloatField(default=0, verbose_name='Макс. температура (°C)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microcontroller',
            name='min_temp',
            field=models.FloatField(default=0, verbose_name='Мин. температура (°C)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microcontroller',
            name='name',
            field=models.CharField(default=0, max_length=100, verbose_name='ID на схеме'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='microcontroller',
            name='max_pressure',
            field=models.FloatField(verbose_name='Макс. давление (Атм)'),
        ),
        migrations.AlterField(
            model_name='microcontroller',
            name='min_pressure',
            field=models.FloatField(verbose_name='Мин. давление (Атм)'),
        ),
    ]
