# Generated by Django 5.2.4 on 2025-07-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_microcontroller_display_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microcontroller',
            name='display_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
