# Generated by Django 5.2.4 on 2025-07-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_microcontroller_display_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microcontroller',
            name='display_id',
        ),
    ]
