# Generated by Django 5.2.4 on 2025-07-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_remove_microcontroller_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='microcontroller',
            name='id_device',
            field=models.CharField(default=0, max_length=100, verbose_name='id положения конроллера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='microcontroller',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя на схеме'),
        ),
    ]
